# Generated by Django 4.1.7 on 2023-04-11 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название диагноза')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание диагноза')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Способ лечения')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('iin', models.CharField(max_length=12, null=True, unique=True, verbose_name='ИИН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=12, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='xrays/', verbose_name='Рентгеновский снимок')),
                ('result', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Результат')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Снимок пациента',
                'verbose_name_plural': 'Снимки пациентов',
            },
        ),
        migrations.CreateModel(
            name='XRayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий доктора')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечен ли доктором')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.diagnosis', verbose_name='Диагноз')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Доктор')),
                ('x_ray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.xray', verbose_name='Рентгеновский снимок')),
            ],
            options={
                'verbose_name': 'Заявка на рассмотрение доктора',
                'verbose_name_plural': 'Заявки на рассмотрение доктора',
            },
        ),
    ]
