# Generated by Django 4.1.5 on 2023-01-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название диагноза')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание диагноза')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Способ лечения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.patient', verbose_name='Пациент')),
            ],
        ),
    ]
