# Generated by Django 4.1.5 on 2023-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
