# Generated by Django 4.1.7 on 2023-04-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayrequest',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Отвечен ли доктором'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='xray',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.patient', verbose_name='Аккаунт пациента'),
        ),
        migrations.AlterField(
            model_name='xray',
            name='photo',
            field=models.ImageField(upload_to='xrays/', verbose_name='Рентгеновский снимок'),
        ),
        migrations.AlterField(
            model_name='xray',
            name='result',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='xrayrequest',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='xrayrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='xrayrequest',
            name='x_ray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.xray', verbose_name='Рентгеновский снимок'),
        ),
    ]
