# Generated by Django 4.1.7 on 2023-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_xrayrequest_is_answered_alter_patient_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayrequest',
            name='doctor_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий доктора'),
        ),
    ]
