# Generated by Django 4.1.5 on 2023-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_diagnosis_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=12, null=True, verbose_name='Пол'),
        ),
    ]
