# Generated by Django 4.1.5 on 2023-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_patient_birth_date_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
